### PR TITLE
Update sk-plugins-last-updated-column.php

### PR DESCRIPTION
**Pull request by jb510**
Fix for: https://wordpress.org/support/topic/004-update-broke-my-plugins-page?replies=2

Please note, this is 100% untested I wrote it on GitHub and PR'd you on it, so please do test before pushing to .org.

### CODE REVIEW

**Comment by fastmover** [comment]
Lol, well it won't load the plugin with this fix....

**Comment by jb510** [comment]
Ha, well I did say I wrote it freehand on GitHub and hadn't tested it.  If you need a hand just ask. I'll pull down the plugin and actually debug that code.

**Comment by fastmover** [comment]
The issue being i wrote code for php 5.3.3 and above, if you know a way around the DateTime::diff() method then by all means, please do it.  Just have to refactor how PHP is doing is time differential for versions older than 5.3.3.

**Comment by jb510** [comment]
http://stackoverflow.com/a/5548143/554469

Personally I mostly write bespoke plugins for individual clients and am just used to checking for PHP 5.3+ to be safe and then bailing.  

Danny has a nice bit of code for that here:
https://github.com/dannyvankooten/wp-mailchimp-top-bar/blob/master/mailchimp-top-bar.php
https://github.com/dannyvankooten/wp-mailchimp-top-bar/blob/master/php-backwards-compatibility.php

It's nicer than what I've been doing and I'm going to adopt something more like his.

**Comment by fastmover** [comment]
This was resolved a while ago.

**Pull request closed without merging**
